name: kohana_generator
description: Kohana code generator.
version: 0.1.1
homepage: https://github.com/sidinaz/kohana

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  path: ^1.6.0
  glob: ^1.1.7
  analyzer: ^0.40.1
#  daggerito:
#    path: /Users/siddik/dart/daggerito
#  kohana_annotations:
#    path: ../kohana-annotations
  daggerito: ^1.0.8
  kohana_annotations: ^0.1.0
  collection: ^1.14.8
  json_annotation: ^3.1.0
dev_dependencies:
  build_runner: ^1.0.0
  build_test:
  mockito:
  test:
