name: kohana
description: State management (flutter_hooks based), validators, common models, event bus, responsive layout and more in one codebase.
version: 1.0.3
author: Siddik Nazdrajic <s.nazdrajic@gmail.com>
homepage: https://github.com/sidinaz/kohana
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  routex: ^1.0.9
  daggerito: ^1.0.5
  rxdart: ^0.23.1
  flutter_hooks: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter